### ISSUE TITLE
Generate optimised thumbnail from user avatar

### ISSUE THREAD

**Issue by willm30** [JoinColony/colonyCDapp#142]
Creating this issue so we don't lose visibility of this. 

Currently when uploading a user avatar at `edit-profile`, the thumbnail doesn't update. 

I believe this is because we would like to implement an automatic thumbnail generator, presumably in a custom lambda function designed for that purpose. [details tbc]

So, the flow would be to upload an avatar, and then the lambda function will upload the avatar to the db and also generate an optimised thumbnail, and upload that also to the user's profile. This would ensure the thumbnail img is updated at the same time as the user uploads an avatar. 

## TODO

- [x] Research library for thumbnail optimisation 

### [Squoosh api](https://github.com/GoogleChromeLabs/squoosh/tree/dev/libsquoosh)

Probably my no.1 if its bundle size weren't 12mb. Maintained by google, I've actually used it before in the browser, it's very good; however, 12mb is too big, surely. It's also marked as experimental so perhaps best to avoid in production for now.

### [Sharp](https://www.npmjs.com/package/sharp)

Heard of this when using Gatsby as their official image plugins are built on top of it. Looks like it is node only though.

### [Jimp](https://www.npmjs.com/package/jimp)

1mn weeky downloads, 12k stars, and can run in the browser. But 3mb bundle.

### [Pica](https://www.npmjs.com/package/pica)

3k stars. 216kb bundle.

**Comment by willm30** [comment]
@rdig Can I confirm I understand this correctly? I.e. the intention is to create a lamda function to handle the thumbnail generation / optimisation based on the avatar the user uploads?

**Comment by rdig** [comment]
So I actually didn't give this a proper think.

We can generate the thumbnail both in the lambda function, on upload, and both in the client, and then sending both files. _(client side works in this case since it's a one-time thing, so won't cause mass processing overhead)_

Both are ok, and both are doable, and I don't really have a strong argument towards one or the other.

You have any thoughts on this ?

**Comment by willm30** [comment]
@rdig If it were as simple as the following (pseudo-code)

``` tsx
import generateOptimisedThumbnail from 'some-external-library-or-local-util'

const newAvatar = formValues.avatar
const optimisedThumbnail = generateOptimisedThumbnail(newAvatar)

updateProfileMutation({
   avatar: newAvatar
   thumbnail: optimisedThumbnail
})

```

Then I would actually opt for client for the sake of simplicity. Especially if the call to optimise the thumbnail was small and quick.

Did you have a library or anything in mind to do the optimising, or should I add this as a task to research in this pr? And what do you have in mind by "optimise"? E.g. reduce file size?

**Comment by rdig** [comment]
It should work similar to your pseudo code sample over there, so I good to have inside the client.

As for library I don't have one in mind. 

I do remember us _(and by that I mean Alex)_ writing a small JS script that created thumbnails out of images _(but it could only handle squares)_. 

But then again, in the time since then, most likely more feature complete libraries have been written, so yes, please at this as a "research" phase of this issue.

As for optimization we're looking for 3 things _(arguably just 2)_:
- reduce in actual image size _(128x128px)_
- compress final thumbnail up until it starts loosing accuracy
- reduce in file size as much as we can _(but this should actually be a side effect, since the previous two points will actually help us reduce the file size, without having to do anything else to facilitate this)_
