### ISSUE TITLE
Global: Broken team actions & widgets

### ISSUE THREAD

**Issue by melyndav** [JoinColony/colonyCDapp#1777]
## Description

The latest prod release has broken teams across a number of areas within the CDapp. 

1. The team switcher is showing blank teams in the dropdown: 

<img width="532" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/152d5b2e-b8f3-4dfd-9ef4-da25b8aebd91">

![image](https://github.com/JoinColony/colonyCDapp/assets/82127904/405b05bb-327b-452e-935f-1856b84ce2cc)

2. The blank teams are showing up in the team widget incorrectly:

<img width="380" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/bc2d9673-6266-4185-b44e-c88e130f1c71">

3. The teams are also showing broken in the widget on the members page 
<img width="276" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/f672240f-ff69-451b-9cac-979503f97b57">

4. The edit a team action is breaking when completed:

![image](https://github.com/JoinColony/colonyCDapp/assets/82127904/c80c0789-8dee-4706-9807-b6d780ad208f)

 5. When editing a team after selecting it from the teams page, it does not pre-fill the action type anymore.
 
 
<img width="713" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/2d094d6d-f7ca-40ca-9ef3-590990896e48">

**Comment by rdig** [comment]
At least when it comes to Private RC,  this is not a UI issue, it's a database problem.

That domain was created it the first few moments after the launch when we had trouble uploading data, hence metadata was not created for it.

We'll investigate deadlabs specifically as well, but this has a different fix, as the UI works as expected

**Comment by melyndav** [comment]
@rdig there is some discussions here with further info. The user also tested editing names with no luck - https://discord.com/channels/562263648173555742/1172535961519915028/1199375010872176713

**Comment by rdig** [comment]
Yup this is indeed a issue, and can replicate the same thing that the user in the Discord reported

![Screenshot from 2024-01-24 20-56-55](https://github.com/JoinColony/colonyCDapp/assets/1193222/827429a7-92a9-4b86-b780-7d148bdab8a6)
![Screenshot from 2024-01-24 20-57-05](https://github.com/JoinColony/colonyCDapp/assets/1193222/37e48a43-1747-4dd0-8bf8-2804d8307c49)

This however seems to be a issue affecting production only _(I can't seem to replicate it locally)_, however just because I can't replicate it, doesn't mean it can't be replicated.

So whoever ends up picking this up, make sure you rope @bogdan-1337 in on this, as you'll need his help poking inside metadata tables and lambdas
