### ISSUE TITLE
Incoming funds not working in production

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyCDapp#1797]
## Description

This was experienced by a Beta user in the Deed3Labs colony `/deed3labs/` in production, where incoming funds were not picked up in the UI.

A payment of $1 in xDai and $10 in USDC was made to the Colony but not appearing in the Colony.

Both tokens are being managed by the Colony and and are visible in the Balance page. Filtering in the incoming funds table has no impact on the results shown.

- Balance can be seen here - https://gnosisscan.io/address/0xeB38458F4E88fCa8C69D39AC2D477009b5a3010D#internaltx
- xDAI transaction is here - https://gnosisscan.io/tx/0xcdb1752ec53b0f1dfb949579814d203a574f1fda3cedd9053350df55870b4ff1
- USDC transaction is here - https://gnosisscan.io/tx/0x0e914d5a5f0c622d8e1a9495a7ae141acb47f0c348e0eae9c07ee877874c8049

While, this can be claimed manually via a contract call I am holding off from doing this for now to give us a chance to see what the issue is and that it does not relate to the same issue experienced in the DApp.

**Comment by jakubcolony** [comment]
List of things to be fixed in order to make transfers work:
- block-ingestor not matching `Transfer` events to the listeners properly
- `Transfer` event handler not ensuring token exists in the DB
- Fix the existing token listener check in `addTokenEventListener` (it only allows 1 listener at the moment)
