### ISSUE TITLE
No user feedback provided when upgrade colony motion finalisation is invalid

### ISSUE THREAD

**Issue by iamsamgibbs** [JoinColony/colonyCDapp#1802]
## Steps to reproduce

- Create two motions to upgrade the colony, and move them both to the 'execution' step.
- The first one can be finalized
- The second one cannot (which is the correct contract behaviour), but clicking the 'Finalize' button appears to do nothing in the UI, and logs the voting-execution-failed-not-one-week error that occurs when (presumably) estimating gas to the console. Repeatedly clicking the button is possible, and has the same effect each time. I don't believe this is actually broadcasting a transaction though, so users will not be losing gas fees, just getting confused.

(Initially observed when testing #1741 - will need to follow setup steps in #1677 to have a colony which needs upgrading)

https://github.com/JoinColony/colonyCDapp/assets/34915414/fccedab5-9613-4716-ad4e-258b1504c332

## Expected behaviour

* When clicking the 'Finalize' button, it should fail to finalise (as the upgrade will have already occurred in the previous motion). A clear error should be displayed to the user as to why it is not possible to finalise this motion.
* The voting-execution-failed-not-one-week error should not occur in the console.

## Actual behaviour

* When clicking the 'Finalize' button, from a user perspective nothing appears to happen.
* The voting-execution-failed-not-one-week error occurs in the console.

**Comment by rdig** [comment]
This is a good observation, but it's not necessarily related to the version upgrade motion, but more specifically it relates to all motions, from the perspective of the UI

This is a bit tricky, since if you look in the gas station _(userhub / transactions)_, you'll see the transaction fail, with the appropriate error message.

So the problem here is more than the transactions list is not being properly displayed in case of an error, as that's the place where all transaction related errors should be.

Secondarily, the "Finalize" button should be disabled, but that's not relevant in this issue, as that is going to be tracked separately as part of #1803 _(Details still need to be updated)_

**Comment by rdig** [comment]
So I'd redo this issue as "Ensure Transaction List from User Hub is showing in care of a transaction errror"

**Comment by iamsamgibbs** [comment]
Ah okay! I've tested it out and seen the transaction failure message in action so that makes more sense now. I've remade this ticket as #1807 (if there are any simpler steps to reproduce this state, let me know and I can adjust the new ticket) so will close this one now.
