### ISSUE TITLE
Team reputation donut not displaying on Arbitrum 

### ISSUE THREAD

**Issue by melyndav** [JoinColony/colonyCDapp#2220]
## Description

Within the new Betacolony on Arbitrum, the team reputation donut is not displaying for all teams on the main dashboard.

<img width="1349" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/65318c68-77de-431e-9606-0f0f38967aa1">

<img width="409" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/f4dacdaa-fc38-4ef9-a4d4-ade6dffbd31e">

**Comment by rdig** [comment]
Nothing to do with Arbitrum. This is a general that always existed. It's because you don't have a second team with a positive reputation value _(operations in this case is at 0)_

Once Operations will get some reputation, the donut chart will start rendering.

Here's RC colony on Arbitrum, where two separate subdomains have positive reputation:

![Screenshot from 2024-04-11 13-23-28](https://github.com/JoinColony/colonyCDapp/assets/1193222/217e6fcd-d0b4-4688-b3ca-6f9c79f7d8b2)

**Comment by arrenv** [comment]
Came here to say the same thing, this is needing an improvement in how we handle single teams with reputation.

I will close this for now and raise a separate issue with an updated spec to handle this.
