### ISSUE TITLE
Advanced Payments API: Determine the limit for CSV batch payments

### ISSUE THREAD

**Issue by jakubcolony** [JoinColony/colonyCDapp#2250]
## Specification

With CSV uploads, it is expected we will hit limit on transaction size at some point, after which the transactions will have to be split in order to be sent.

This issue is to establish such limit and if it's lower than the required 400 CSV rows, implement a work around.

**Comment by arrenv** [comment]
@jakubcolony Adding to this, I have experienced the immediate payments not able to be made due to I suppose the payment limit. The unpaid amounts show as payable, however, when you click on "Make payment", the UI gets stuck in a pending state, no transaction is triggered and no payout is made.

![image](https://github.com/JoinColony/colonyCDapp/assets/33682027/07916d50-ee44-4645-a97c-dfb390c3af94)

![image](https://github.com/JoinColony/colonyCDapp/assets/33682027/d99c4b52-667d-4d62-a9e7-00ec6329e5e6)
