### ISSUE TITLE
Balances is calculating incorrectly in the UI

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyCDapp#2298]
## Steps to reproduce

1. Take note of the balance in a colony. (A round number will make it easier)
2. Make a payment action and execute it.
3. Check the balance again, it should show the correct balance removed.
4. Reload the page, the balance will be less 2 x payment amount.

The issue is not within domains.

## Expected behaviour
* The balance should show correctly as of what the correct balance is on chain.

## Actual behaviour

* You can see the flashing of the value change where double deducting of values is happening
![value-incorrect](https://github.com/JoinColony/colonyCDapp/assets/33682027/7f31926a-70ea-416b-b9c8-873f38ad2e72)

* Domains are showing the correct value being deducted
![image](https://github.com/JoinColony/colonyCDapp/assets/33682027/91e6846a-6574-492f-bf8f-48e453b8eb46)

This looks to have been Introduced in this PR: https://github.com/JoinColony/colonyCDapp/pull/1922/files#diff-d51f4db8269ce4854a3d43363cd407e5d4906f9a9fbb4554e2222a66405cb86d
This is the relevant logic here - https://github.com/JoinColony/colonyCDapp/blob/1a93e6e265ebe91332b143acacd42dccc95f418f/src/components/frame/v5/pages/BalancePage/partials/BalanceTable/hooks.tsx#L46

**Comment by rdig** [comment]
Fixed by @jakubcolony 's https://github.com/JoinColony/block-ingestor/commit/39d459679c3133ccea79666108db24fc79ba4fba and pulled into the CDapp via https://github.com/JoinColony/colonyCDapp/pull/2120/commits/a9a935af19a19b632800d26bffbbc60f2d1df52e

This issue will eventually get it's own PR and be closed, once I end up merging the arbitrum changes back into `master`
