### ISSUE TITLE
UserHub Stakes tab issues - padding, overflow, filtered and status pill issue

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyCDapp#2566]
## Steps to reproduce

1. Ensure you have staked motions on your account.
2. Open up the UserHub Stakes tab.
3. Check for padding, overflow, and status pill issues.
4. Check that all claimable transactions are listed across all colonies.

## Expected behaviour

* Padding of items in the list should match the design.
* The items in the list should not overflow the container.
* The pills should show the correct status.
* The list of claimable motions should be visible across all colonies

## Actual behaviour

* Padding does not align with the design, and there
* The items in the list should not overflow the container.
* The pills should show the correct status.
* You only see staked actions that are in the current colony context.

![image](https://github.com/JoinColony/colonyCDapp/assets/33682027/a26f813e-5ebc-414c-98c9-c4428d23cfaa)

![image](https://github.com/JoinColony/colonyCDapp/assets/33682027/47bd9ed5-0516-4c9f-b066-8b1f26821013)

**Comment by Nortsova** [comment]
Hey @arrenv!

The UI part looks clear.

However, regarding the status and "Check that all claimable transactions are listed across all colonies," I found a couple of edge cases I'd like to discuss:

1. In the MultiSig branch (in PR #2737), there was an implementation that would show an "Uninstalled" status for uninstalled extensions.

Before uninstall:
<img width="680" alt="image" src="https://github.com/user-attachments/assets/76d0f066-cc9e-495c-824e-33325be0f71f">
After uninstall:
<img width="456" alt="image" src="https://github.com/user-attachments/assets/2fef040b-5a4d-4ccf-9e97-513019e403e8">
<img width="1013" alt="image" src="https://github.com/user-attachments/assets/fbb82dfa-4ffc-460a-825d-c8df5ad860cc">

Currently, it seems like this status exists in the transaction, but not in the Stake tab. Therefore, I plan to replace "unknown" with "uninstalled" in this case.

2. Example:
A user created a Stake in Colony A.
<img width="1143" alt="image" src="https://github.com/user-attachments/assets/e0cbaf71-64b4-4067-8dc9-fe5e3c9fe1f1">

Then, they went to Colony B and opened the User Hub.
<img width="1143" alt="image" src="https://github.com/user-attachments/assets/9f86a02d-0502-429a-b769-cd916dd784d5">

It seems obvious that the user can't manipulate stakes from a different colony than where the stake was created. Can we consider this flow a bit more? What kind of statuses should be displayed instead of "unknown" or "uninstalled"?

(Sorry for using motion screenshots instead of User Hub, but these are just to show the statuses.)

**Comment by arrenv** [comment]
@Nortsova Good pickup and good question. From what I can tell, what is happening is that a transaction from Colony A is opening in Colony B. Which, really should not be the case. I feel as though the simplest solution to this issue should be that if you click on a transaction in the UserHub from another colony you should be directed to that transaction on the other colony.

E.g. from your last screenshot, this should have redirected to the planex colony as opposed to staying on wayne and trying to show the transaction.

![image](https://github.com/user-attachments/assets/b4c7bfdd-07f5-48fd-bbfb-b4750c41f63d)
