### ISSUE TITLE
User has rewards, but, it is not showing in the UI

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyCDapp#2645]
## Steps to reproduce

1. Create a new action with the Reputation decision method.
2. Fully Support and Oppose to get to voting.
3. Switch to a different user and vote on the intended winning side. (make sure the user 'Amy' does not have more rep than the threshold)
4. Switch back to the previous user and vote on the intended winning side. (easier if this user 'leela' does pass the voting threshold as you will progress to the reveal stage.)
5. Reveal your vote.
6. Switch back to the other user.
7. Reveal vote. Also, note that you should have some reward, even though you didn't stake.
8. You should be able to finalize. (See this issue https://github.com/JoinColony/colonyCDapp/issues/2644)

## Expected behaviour

* Tokens that the user is able to claim, should show up in the stakes tab.
* Users who vote but don't stake and are on the winning side should receive a reward and it should show in the staking overview of a motion.

## Actual behaviour

* The user has rewards that they should be able to claim, the rewards do not show up as claimable in the stakes tab. I was having finalizing this scenario, so, could be resolved with the issue #2644)
* Users rewards are not showing in the motion staking overview.

![image](https://github.com/JoinColony/colonyCDapp/assets/33682027/1b3f81c7-9eea-4e7a-ac29-743ce65d2b4d)

![image](https://github.com/JoinColony/colonyCDapp/assets/33682027/59f64077-25ac-4782-9107-9a856bfe3ba6)

![image](https://github.com/JoinColony/colonyCDapp/assets/33682027/15b872fa-e5a7-4139-b975-4e8017cc432a)

**Comment by arrenv** [comment]
Also raised in this PR https://github.com/JoinColony/colonyCDapp/pull/2585, but will treat as a separate issue here.

**Comment by bassgeta** [comment]
Dropping a comment with the latest findings.
Basically you can't "claim" these rewards, since you automatically get them after revealing your vote.
We agreed with @arrenv  upon doing 3 things:
1. 

![Image](https://github.com/user-attachments/assets/230c7998-1933-4f40-8dec-d526515f50c5)

This should say `Your overview` and should include voting reward info
2.

![Image](https://github.com/user-attachments/assets/dda8b70e-a8c0-47e8-b05d-c1c415b19dad)

This should include the voter reward under the `Reward` row's value
3. 

![Image](https://github.com/user-attachments/assets/b50618a3-0a8a-43e8-bc0e-8f11d807dcf5)

The user hub should display user's voter rewards (needs block-ingestor tweaking)
