### ISSUE TITLE
[Multi-sig] Extension is not enabled if "Enable permission" transaction using Metamask is rejected

### ISSUE THREAD

**Issue by mmioana** [JoinColony/colonyCDapp#2754]
When testing it with metamask, if you approve the first transaction, then reject the second you get into this weird state where the extension is installed, but not enabled but the 'Enable permissions' banner never shows.

If you go back to the dashboard, refresh then navigate back to the extension page, then it will instantly trigger the 'Extension enable' transaction when the page loads - I think at this point it would be better to show the 'Enable permissions' banner rather than instantly triggering a transaction - as a user it is unclear why a transaction has started.

Also - if you navigate directly to the page (rather than coming from another page), then it seems the network client isn't available in time for things  to function as expected:

<img width="1728" alt="Screenshot 2024-07-22 at 16 03 08" src="https://github.com/user-attachments/assets/5ac4d2c1-5d21-4f77-889e-7884796201fc">

After accepting the transaction, the extension is enabled correctly.

Here is a video of me testing this:

https://github.com/user-attachments/assets/cfcd44a4-47b7-4dec-bcba-a19c552da1ae

It probably isn't worth the effort of fixing it right now, it is probably very unlikely a user would accept the first transaction and reject the second (although it could happen if they lacked funds for the second transaction). And it is at least possible to finish enabling the extension if they get into this situation, so it doesn't completely break the app - even if the steps for this aren't immediately clear.

_Originally posted by @iamsamgibbs in https://github.com/JoinColony/colonyCDapp/pull/2694#pullrequestreview-2191919842_

**Comment by rdig** [comment]
Nice catch

**Comment by rdig** [comment]
To re-check since it might already be resolved

**Comment by iamsamgibbs** [comment]
I don't believe this to be an issue anymore due to the extensions refactors and `ExtensionInstallAndEnable` saga.

However, it is possible to get into a state where the extension has installed but the `setUserRoles` transaction is rejected, meaning the `onSuccess` function never runs to update the page to remove the install button, show the extension settings tab, etc. It does appear on a refresh so it a much less severe issue than this original ticket.


https://github.com/user-attachments/assets/d66c5aea-977d-4480-b5bd-dbf95341ac1c

After a refresh, the missing permissions banner appears as expected and will properly assign permissions which was the main problem described in the original ticket.

I'll investigate adding a handler / adapt the onError handler, for the scenario where the extension install transaction succeeded, but the setUserRoles transaction failed.
