### ISSUE TITLE
Buggy motion voting flow 

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyCDapp#2883]
## Steps to reproduce

1. Create a new action with the Reputation decision method.
2. Fully stake and oppose the motion to take it to vote.
3. Vote in support.
4. Note that you need to sign twice, despite the pending button showing only one.
5. Note that the UI did not update automatically, I had to reload the app to update the status.
6. After reloading not that the UI does not inform you of your vote. It shows a Support button and the change vote button.
7. Click on the "Support" button then click the "Change Vote" button.
8. Complete the transactions.
9. Your vote will change and you will see the correct state.
10. Now, without clicking the "Oppose" button, click the "Change Vote" button.
11. Note that nothing will happen, but there are no errors or validation.

## Expected behaviour

* The UI should accurately show the number of wallet signatures required.
* The UI should update automatically when a transaction as succeeded that should update the status of the vote and motion.
* The voting widget should show the users vote and the text explaining they can change their vote.
* We should remove the single option after voting and when wanting to change votes. The UI, should just handle that when the user clicks "Change Vote" it should change to the opposite of their current vote. As if the below design.

![image](https://github.com/user-attachments/assets/ea861351-b90a-40b3-9d91-0178c7c3da40)

## Actual behaviour

* There are two wallet signatures required, but the pending button only shows 1.
* Sometimes voting does not update the UI automatically.
* There is missing content after the initial vote (this did not seem to happen every time).
* There are no errors or validation if you don't select the only option when changing vote.

[voting-flow.webm](https://github.com/user-attachments/assets/41a4f020-0107-410a-a0bc-d4073068a5c8)

**Comment by iamsamgibbs** [comment]
Just a note that the UI issues have been resolved by #3108

The incorrect pending count will be addressed in a separate PR

**Comment by iamsamgibbs** [comment]
I've spent some more time looking into the issue with the "Pending" button showing the incorrect number. I think this will be quite complex to fix and doesn't feel like a high priority issue right now. I suggest creating a new issue for this which we can fix at a later point. Thoughts? @arrenv @rdig 

To summarise the issue and potential fix:

The "Pending" button does not show the "correct" count because the first metamask popup is a **signature** rather than a **transaction**. The first number in the "Pending" button is determined by the number of transactions in a group that do not have the "Success" status. The second number is the total number of transactions in the group.

Ideally the signature would also show in the UserHub transactions list and could be retried if the signature was rejected.

A possible fix would probably be to add a new "Signature" model to the schema which would store the transaction group id, index, status, etc. Then when we query the transactions we would create an array of all the transaction groupIds which could then be used to query the signatures for any matches. We could then combine the transactions array with the signatures array to correctly show to show the correct pending count, and also show them in the userhub transactions list. This is quite a lot of work for a small win and it feels like there are higher priority issues right now.

**Comment by arrenv** [comment]
@iamsamgibbs I feel this is a very low priority issue and would suggest we create a separate issue for it and review it at a later date if it becomes an issue.

**Comment by iamsamgibbs** [comment]
Created new issue #3115 so will close this one up!
