### ISSUE TITLE
User balances delayed updating in Userhub

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyCDapp#3118]
## Steps to reproduce

Note: This is not something that happens every time, however, both Etienne and I have both experienced it live on user calls and I have seen it at least once. It seemed to resolve itself for the user after several hours.

1. In production, create a payment to yourself in the colony's native token.
2. Open the Userhub and check your balance.
3. Check that the balance reflects the payment made.
4. Return to the app in couple of hours.
5. Open the Userhub and check your balance and reputation.
6. Note, you will have updated reputation but not an updated balance.

## Expected behaviour

* Userhub balance should update right away within the app, without needing to reload or wait several hours.

## Actual behaviour

* The Userhub balance is not updating correctly for some users.

![image (1)](https://github.com/user-attachments/assets/3ea2a20f-9546-49d3-a9f2-cd8bd4982a36)

**Comment by iamsamgibbs** [comment]
I suspect this may have been fixed by this commit from @jakubcolony   https://github.com/JoinColony/colonyCDapp/commit/8c852c4ee0080363e9b34542853a3115b167832e which was only merged into master a couple of weeks ago as far as I can tell. It changes the fetch policy from the default `cache-first` to `cache-and-network` which would explain why users were receiving stale data.

If others agree with my assumption then I would suggest we close this issue and re-open it if it happens again. @arrenv @rdig

**Comment by arrenv** [comment]
I have not been able to replicate and have not had any issues raised recently about it, so, no strong objections from me if Jakub's fix likely resolves it.

**Comment by rdig** [comment]
Closing it. Nice sleuthing @iamsamgibbs :+1:
