### ISSUE TITLE
Not able to pay out owed Streaming funds too soon to claim error

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyCDapp#3140]
## Steps to reproduce

1. Create a Streaming funds action.
2. Ensure there are funds to claim.
3. Click on the Pay funds button.
4. Not the console logs or transaction tab for any errors.

Note: I used "Start immediately" as the start condition. The contract test for this particular error is a result of "cannot claim a streaming payment before the start time"

## Expected behaviour

* You should be able to claim funds that are owed.
* If there is a reason for not being able to pay the funds, we should provide validation to the user.

## Actual behaviour

* You are not able to pay out claimable funds for streaming funds. The error received is "streaming-payments-too-soon-to-claim".

![image](https://github.com/user-attachments/assets/fe6fb949-75fa-434f-b23e-04e838542668)

**Comment by jakubcolony** [comment]
This was a local dev issue where we couldn't retrieve the correct blockchain time due to a bug in the ethers provider (see #3133). As a result, if you chose "Start immediately," it would set the start time to the current system time, which was much ahead of the local block time. So, from the contracts' perspective, it was indeed too early to claim.

The issue was resolved by rebasing feat/streaming-payments and pulling in the fix from #3133.
