### ISSUE TITLE
[Dashboard] Dividers aren't shown on mobile in the Recent Activity section of the dashboard

### ISSUE THREAD

**Issue by olgapod** [JoinColony/colonyCDapp#3487]
## Steps to reproduce

1. Open the dashboard on a mobile device
Navigate to the Recent Activity section
Observe the absence of dividers between items

## Expected behaviour

* Dividers are shown on mobile in the Recent Activity section of the dashboard

## Actual behaviour

* Dividers aren't shown on mobile in the Recent Activity section of the dashboard

<img width="994" alt="image" src="https://github.com/user-attachments/assets/3b0fd3a5-2095-4136-beec-aba8a5e49871">

**Comment by rdig** [comment]
Please confirm with @melyndav this actually a bug and not a design choice for mobile

**Comment by melyndav** [comment]
@rdig this is a bug - https://www.figma.com/design/gac6xVgGNCAge5Bia933dp/Dashboard?node-id=7137-44861&t=Lg6kPqJBXmaDt5jx-4

@olgapod can you please kindly provide Figma links for ALL UI/UX issues so they can be reviewed and referenced by @rdig and the assigned dev when the issue is picked up? This helps to avoid the double handling of issues. Thank you! ☺️
