### ISSUE TITLE
QA Dashboard: Team name fallback issue

### ISSUE THREAD

**Issue by melyndav** [JoinColony/colonyCDapp#3510]
## Description

When creating a new team, the transaction failed with a JSON RPC error. When re-trying the transaction again to create the same team, the transaction was successful, however the team name wasn't saved, and it's showing as an unknown domain.

<img width="1504" alt="image" src="https://github.com/user-attachments/assets/397c76e7-c755-40e6-8bb4-0e013a005624">
 
<img width="1314" alt="image" src="https://github.com/user-attachments/assets/42381f62-f509-4139-83da-433bcd32252a">

## Steps to reproduce 

It's happening reliably, three transactions in a row, when trying to create a new team directly from the dashboard team widget. 
 
 1. Create a new team and complete the action.
 2. Sign the metamask tx.
 3. TX fails and shows JSON RPC error in userhub.
 4. Retry the action again by clicking the CTA button inside the action and not retrying from the user hub.
 5. Sign the metamask tx.
 6. TX is successful, however, the fallback is shown in the UI with the Colony address and domain ID. 
 
## Expected behaviour 
 
Fallback for teams that don't have a name should be in the format of : "Team #{domain_ID}"

## Actual behaviour

<img width="1365" alt="image" src="https://github.com/user-attachments/assets/9510f19b-65f2-43a6-b851-5076a55a0bca">

Broken team name showing in team select dropdown:

<img width="500" alt="image" src="https://github.com/user-attachments/assets/ce16f548-e25f-40af-af5b-bee10db0f518">

**Comment by iamsamgibbs** [comment]
Time to open a can of worms.

The issue here is that the `DomainMetadata` (name, colour, description) does not get created when retrying a `Create team` transaction from the UserHub.

We can add fallbacks for team name / colour / description wherever they are used but we are just masking the actual issue.

The proper fix here would be to either ensure the DomainMetadata is properly created when retrying a `Create team` transaction from the UserHub but I'm not sure how feasible this is given how the retry system is currently setup.

To make the issue worse, because there is no `DomainMetadata` entry for the team, the `Edit a team` action will fail because it tries to mutate the existing entry rather than creating one, so even after adding fallbacks, further changes to the EditDomain action will be required to create the entry if it does not already exist (which is probably worth doing either way to be honest).

This is worth reviewing though as it will affect any saga that performs a database mutation following a successful transaction, and maybe we should disallow these from being reattempted from the userhub, or refactor the userhub to allow for a more robust retry system.

I would suggest that this requires further discussion and for now a short term solution would be to manually create a `DomainMetadata` entry for any users that run into this niche edge case issue.

Thoughts @rdig @arrenv @melyndav ?

**Comment by rdig** [comment]
Yeah, let's set up a call because there's multiple implications here.

I have a few ways to go about this but not really sure which are better, so maybe we can bounce some ideas off each other.

However, give the number of QA issues we're already dealing with I suggest de-prioritizing it for this cycle and re-visiting it in the next one

**Comment by arrenv** [comment]
Thanks for the thorough breakdown. Given we can fix it for users manually, I feel it is reasonable to de-prioritize for this cycle.

I feel it would be better to resolve the problem of the original transaction failing then just a symptom of it anyway.
