### ISSUE TITLE
Refactor `useColonyContext` to return a defined `colony` prop

### ISSUE THREAD

**Issue by ArmandoGraterol** [JoinColony/colonyCDapp#363]
Currently, even though the inner workings of `useColonyContext` would prevent us from getting an `undefined` `colony` prop whenever we use this hook, we still have to check for this prop to be defined in order to use it in some instances in the CDapp, which shouldn't be necessary because if it was `undefined`, then the user would see a 404 page instead of whatever component is checking if the prop is defined or not.

We should take a look into `useColonyContext` to actually return the correct typing for `colony` and with that, we could get rid of all of the unnecessary checks.

**Comment by jakubcolony** [comment]
The inclusion of `undefined` type is, at the moment, correct:

Look at the context declaration and initial value:
```js
interface ColonyContextValue {
  colony?: Colony;
  loading: boolean;
  canInteractWithColony: boolean;
}

const ColonyContext = createContext<ColonyContextValue>({
  loading: false,
  canInteractWithColony: false,
});
```
The default value for colony is `undefined`. The problem with changing it is that the `useColonyContext` is used not only in components that are wrapped in `ColonyContextProvider`, e.g. `UserNavigation`. It is, for example, being rendered on the landing page that naturally doesn't have any colony associated with it. 

Now, even if we change it so that the context becomes undefined when it's not within the `ColonyContextProvider` and colony becomes non-undefined, what I think it's gonna do is just move the checks from checking the colony to checking the entire context, like so:
```js
  const { colony } = useColonyContext() || {};
  // colony still might be undefined here
```
An alternative solution is to change the initial context value to `null` and have the guard inside `useColonyContext` ensure it's not null, and throw an error if it is (it was my original intention, but I seem to have gotten it wrong since there is a defined initial value for the context). This will however break components such as `UserNavigation` and we'd need to add some extra checks to only call it when it's rendered within the colony context.

**Comment by rdig** [comment]
Is this still relevant ?

**Comment by bassgeta** [comment]
probably done via [this PR](https://github.com/JoinColony/colonyCDapp/pull/1685) and we can close it
