### ISSUE TITLE
[Actions - QA] New follower can perform all actions, but results are not reflected in Dashboard

### ISSUE THREAD

**Issue by olgapod** [JoinColony/colonyCDapp#3634]
## Steps to reproduce

1. Join the New colony
2. Perform any actions
3. Open Dashboard

## Expected behaviour

* Followers should have restricted permissions and be unable to perform actions

## Actual behaviour

* Followers can perform all actions without restriction.
Actions taken by followers do not appear in the dashboard, leading to inconsistencies.

https://github.com/user-attachments/assets/73fe6d1e-8e45-4784-9916-c67c00fb9f1a

**Comment by melyndav** [comment]
Hey @olgapod,

After you created the action, the staking widget shows the following message re: no reputation.

<img width="593" alt="image" src="https://github.com/user-attachments/assets/66d0e764-df07-4d64-b480-c47a81a947fd">

The reputation decision method is an open decision method. Anyone is able to use. However, you are not able to stake on it because you did not have any reputation. 

The UI does not reflect anything because the action was not taken/ approved. 

This action won't show in the activity feed (on the activity or dashboard) until it reaches the 10% threshold. 

You could share this action and someone with reputation in the Colony could stake it.
