### ISSUE TITLE
Advanced Payments Table is incredibly slow when there is a large number of rows

### ISSUE THREAD

**Issue by iamsamgibbs** [JoinColony/colonyCDapp#3673]
## Steps to reproduce

* Create an advanced payment
* Add a ton of rows (via CSV is quicker)

## Expected behaviour

* The form should load smoothly

## Actual behaviour

* The form becomes incredibly laggy and takes a long time to load in via CSV

https://github.com/user-attachments/assets/59e005b7-9019-48ca-8840-90dd4a406379

<img width="1356" alt="Screenshot 2024-11-07 at 14 42 39" src="https://github.com/user-attachments/assets/2162b6ef-c88a-4bd9-abc6-cfe59fcc7497">

<img width="672" alt="Screenshot 2024-11-07 at 14 47 55" src="https://github.com/user-attachments/assets/c7c5818d-4683-47bc-b7c7-9325d093a2b7">

<img width="675" alt="Screenshot 2024-11-07 at 14 48 05" src="https://github.com/user-attachments/assets/1e4e19fe-78d4-449b-8ee7-378f319eda81">

Payments also seem to be coming in in the incorrect order on the completed action screen too (should be starting from 1 not 37), I'm hoping it is somehow related to this laggy behaviour and will work properly once it is resolved rather than being a deeper issue:

<img width="682" alt="Screenshot 2024-11-07 at 14 55 57" src="https://github.com/user-attachments/assets/351e0475-fa6e-4941-8c67-aa05a19479c6">

**Comment by rumzledz** [comment]
Hey @iamsamgibbs I got intrigued by this form because you're right, this used to be pretty efficient at handling any number of rows. I remember testing a PR of yours that deal with uploading a CSV file with a huge number of rows and it was in https://github.com/JoinColony/colonyCDapp/pull/3076.

I am not confident I'd be able to fix it today and I pretty much won't have time next week because of Thailand but I'll leave a comment about why I think this is happening, based on my quick and initial investigation so far.

I had a feeling that this might due to the advanced payment form's payments array validations so I started from there. I uploaded your 400-row CSV file and took out the `payments` field from the validations schema and low and behold, the slowness got eradicated!

> I took out the block from line 49:
<img width="506" alt="image" src="https://github.com/user-attachments/assets/ea1f2c1d-bbd9-4b8d-a63c-917bf5a7be8a">

I brought it back then through process of elimination, this seems to be the main culprit: `allTokensAmountValidation`

<img width="610" alt="image" src="https://github.com/user-attachments/assets/31ad256d-1bcc-4a88-b763-69aa9cc5cff1">

We might be able to optimise this function if we can take out some (if it's even possible) array-based logic for individual tokens and just do it outside i.e. do it in `useValidationSchema` instead, memoise it then pass it in as a prop to `allTokensAmountValidation`. That way, these heavy array operations inside the `allTokensAmountValidation` don't run `payments.length` number of times.

This is just a humble suggestion though and untested 😅
