### ISSUE TITLE
[Staged payment] Incorrect milestone count - Extra milestone displayed after payment

### ISSUE THREAD

**Issue by olgapod** [JoinColony/colonyCDapp#3718]
## Description
After creating a staged payment with two milestones, the system displays that three milestones were paid, even though only two were initially set up. This discrepancy is confusing and may indicate an error in the milestone tracking or payment processing logic.

## Steps to reproduce

1. Create a staged payment with two milestones(select permission or staking method).
2. Complete the payment process for each milestone.
3. Observe the "Milestone payments" section, where an additional milestone is shown as paid.

## Expected behaviour

* Only the created milestones (in this case, two) should be displayed and tracked under "Milestone payments."

## Actual behaviour

* An additional, nonexistent milestone is marked as "Paid," resulting in a total of three milestones displayed in the UI.

<img width="994" alt="image" src="https://github.com/user-attachments/assets/5fa8bae7-b5bf-47d2-b543-b3de596a61ec">

**Comment by davecreaser** [comment]
Hey @olgapod! Thanks for raising the issue, looks like a super confusing one indeed for users 🤔 

No matter what I do though I can't seem to replicate it. Could it be that there is some very specific way of replicating or is it maybe fixed by something else by accident? Thanks!

<img width="1069" alt="Screenshot 2024-12-04 at 16 04 57" src="https://github.com/user-attachments/assets/31476088-8210-4b77-b6f4-6a1b633bffec">
<img width="1063" alt="Screenshot 2024-12-04 at 16 07 01" src="https://github.com/user-attachments/assets/a736e01d-9d5a-4155-b43d-ea87c0f7777c">
<img width="1068" alt="Screenshot 2024-12-04 at 16 08 44" src="https://github.com/user-attachments/assets/3fbaba52-e93f-455c-a7f8-c84adbb6ee7d">
<img width="1069" alt="Screenshot 2024-12-04 at 16 20 39" src="https://github.com/user-attachments/assets/2c072858-4d8f-4774-977a-6258d2681ce6">

**Comment by olgapod** [comment]
@davecreaser thanks, I cannot reproduce anymore

**Comment by olgapod** [comment]
@davecreaser I again had this issue today. Unfortunately, I cannot find the proper steps to reproduce  

https://arbitrum-sepolia.colony.io/345/activity?tx=0xb7b30b8d943dbdbe2edcc1c3b7a93b0340a76c51cd0b477fe1ce9ed22b9e3436

https://github.com/user-attachments/assets/20791138-e008-4625-a262-e8e80ffee70e

**Comment by olgapod** [comment]
I close it and add another because I found different steps to reproduce and it seems not related with original
