### ISSUE TITLE
[Permission] User doesn't have ability to make the payments

### ISSUE THREAD

**Issue by olgapod** [JoinColony/colonyCDapp#3774]
## Steps to reproduce

1. Assign the Payer role to the user in Andromeda.
2. Disable "Staking Advanced Payments" and "Reputation Weighted" extentions.
3. User opens staged and split payments.

## Expected behaviour

* The user with the required permissions should be able to create a payment without encountering the permission error in Andromeda team.

## Actual behaviour

* The system displays an error message, preventing the user from creating a payment despite having necessary permissions.

<img width="1709" alt="image" src="https://github.com/user-attachments/assets/8718ec95-c933-4c91-a99d-7bb19337ecb4">

**Comment by rumzledz** [comment]
Hey @olgapod ! This is definitely a nice find 👌 However can I please get some guidance because I'm only able to replicate this for Split Payments. Simple and Advanced payments seem to be fine (?) (I think)

![only-split](https://github.com/user-attachments/assets/20e5e7be-142f-4bf3-aa06-6e294143221a)

**Comment by olgapod** [comment]
@rumzledz Thank you for checking! I can reproduce the issue today only with split and staged payments. I'll correct the issue
