### ISSUE TITLE
Port and refactor WalletRequiredRoute

### ISSUE THREAD

**Issue by jakubcolony** [JoinColony/colonyCDapp#45]
Currently, there are multiple unresolved imports and warnings.

Most likely blocked by #30.

**Comment by rdig** [comment]
So I've been thinking and this route type is no longer required.

The "wallet required" route was needed because of the legacy way the was was being authenticated (all the time).

Since we no longer have that legacy requirement here (ie; people can browse the dapp freely, without having a wallet connected), there's no longer a need for that route.

(i'm still not sure if it's needed or not for the `/create-user` and `/create-colony` route, but otherwise, it's not required anymore)

So I think you should change this issue to track refactoring all the wallet required routes into always accessible ones (or just normal ones, removing the "AlwaysAccessible" wrapper component altogether. Up to you how you decide to go about it)

**Comment by jakubcolony** [comment]
Thanks for your input @rdig 

I'll close this issue and add your comments to #46
