### ISSUE TITLE
Refetch colony in sagas with mutations

### ISSUE THREAD

**Issue by willm30** [JoinColony/colonyCDapp#511]
If you complete an action, do we need to refetch the colony from the action details page or does the polling update the colony object?

**Comment by jakubcolony** [comment]
I was thinking whether that's relevant for all actions or only the ones modifying something on the colony object (e.g. Edit Colony modifying colony's metadata, Edit Domain modifying colony's domain's metadata, and so on). Otherwise all the data we need to display a particular action should be on the action object, or am I missing something?

**Comment by willm30** [comment]
I.e we can close this, if we're sure all the action sagas have refetches where they should, or change the scope of this issue to ensure that is the case

**Comment by jakubcolony** [comment]
>  we can close this, if we're sure all the action sagas have refetches where they should

I don't think that's the case yet, personally only implemented the in-saga refetch in `manageVerifiedRecipients` and `editColony`. I changed the issue so that it relates to all action sagas with mutations, as these are the ones that need refetching
