### ISSUE TITLE
Port over user's reputation

### ISSUE THREAD

**Issue by jakubcolony** [JoinColony/colonyCDapp#62]
Port over the components responsible for displaying user's reputation:
![image](https://user-images.githubusercontent.com/112586815/199312085-3ec3aaf0-b403-4c05-9480-32034253cd3f.png)

**Comment by rdig** [comment]
Note that fetching a user's reputation will be done via a query resolved by a lambda function. Very similar to what @danbr is doing in #68 

Also, a good idea will be to merge this data, for the currently logged in user, inside the `user` object of the `AppContext` so that it's available wherever the context is available

**Comment by jakubcolony** [comment]
I believe this can't proceed without #68 being done so I added a blocked label

**Comment by rdig** [comment]
@jakubcolony that is not true. They are different things.

Dan's PR is fetching reputation for all users in a colony, all at once

This will fetch reputation for just one individual user at a time
