### ISSUE TITLE
Port Members:Create `getUsersReputationForColony' lambda function

### ISSUE THREAD

**Issue by danbr** [JoinColony/colonyCDapp#68]
## Description

<Partially written to organise my thoughts, maybe it will help others when they embark on porting their first feature to the CDapp>
Create a lambda function to obtain members of a Colony.

`getUsersReputationForColony' 
parameter: Colony address
output: [{ user id, reputation }]

The function should:

- Look up Colony
- get users of Colony (graphQL)
- get reputation of each user from RPC endpoint (reputation miner)
- return clean & organised data

The function skeleton is created using the template provided Amplify.

**Comment by rdig** [comment]
Is this planning to get the reputation for users in all domains at once ? or just for one domain at a time ?

There's also two things I want to mention:
- Once #67 gets implement, this can be merged into the colony object in that provider, and be available everywhere the colony data is available
- we'll actually get some caching benefits out of the box, as since this query will run through Apollo, it will be cached locally by default

**Comment by rdig** [comment]
I also have some ideas on how to deffer member reputation data loading and leverage part of the database to store members, but that involves many more moving parts and should be an optimization for down the line, after everything is implemented.

**Comment by willm30** [comment]
MERGED #111
