### ISSUE TITLE
Members Filter takes up whole screen on mobile view

### ISSUE THREAD

**Issue by willm30** [JoinColony/colonyCDapp#936]
To reproduce: get the members screen on mobile view. Check every single filter in the members filter. Once it reaches the screen length, there's no scroll and you're stuck,

**Comment by rdig** [comment]
Closing as not relevant anymore. Pagepro have take over the mobile view for all pages

**Comment by melyndav** [comment]
@rdig if this issue is still showing in production, it would be ideal not to close any mobile issues but rather assign them to PagePro to fix.

**Comment by rdig** [comment]
@melyndav Since Pagepro is on top of the mobile UI, as well as opening and tracking their own issues, assigning this to them out of the blue would be muddling up the waters, so to speak.

Especially since there were talks about them re-estimating everything that needs to be done related to mobile, just assigning them small issues, which are most likely aware of, wouldn't be productive.

But if you want me to, in the future, I'll assign any mobile UI issues we come across to them, as well as make them aware of said issues.

**Comment by AdrianDudko** [comment]
@rdig @melyndav It works for me to keep mobile issues on GH. And so I copy all the tasks from our Teamwork to GH, so that you can stay up to date and easily check what we are currently working on :)

**Comment by AdrianDudko** [comment]
The issue does not exist anymore.
