### ISSUE TITLE
Connect Wallet button occasionally "sticks" instead of logging in.

### ISSUE THREAD

**Issue by willm30** [JoinColony/colonyCDapp#98]
# Description

This issue is a work in progress as I haven't yet been able to piece together an exact step-by-step to reproduce. 

However, I notice the following sometimes:

![connect_wallet](https://user-images.githubusercontent.com/64402732/203803490-86fccb69-ea4d-466a-9fa0-de97391f0cc5.gif)

## To reproduce (in progress)

Most recently, this happened after switching branches and running `npm i`. The dev environment had already been set up and webpack was already running, so the only changes were the branch switching and running `npm i`. 

## Temp Solution

A quick way to resolve when this happens is to remove `connectOptions` in the connectWallet call, so perhaps something to do with the lastWalletLabel. 

sagas/wallet/index.ts
![connectwallet](https://user-images.githubusercontent.com/64402732/203804110-fd3fd62a-a999-496b-8754-591b9419c755.png)

Once I can reproduce more consistently, I should be able to recommend a proper fix.

**Comment by rdig** [comment]
This is (most likely) because of you switching envrionments between the Dapp and the CDapp. It's local storage "poisoning".

It happens because we share the same local storage key label with the Dapp. Also, this will only be a case for local Dev, since that's the only place were we care about the `connectOptions` label.

I wouldn't worry too much for this honestly, as it shouldn't come up that often. That being said, it can very easily fixed by renaming the CDapp's local storage key name that we use for the last wallet.
